# Generated by Django 4.2 on 2025-10-14 05:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("vehicles", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuctionHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("AUCTION_START", "경매시작"),
                            ("AUCTION_END", "경매종료"),
                            ("TRANSACTION_COMPLETE", "거래완료"),
                        ],
                        max_length=20,
                        verbose_name="액션 타입",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="auction_histories",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="auction_histories",
                        to="vehicles.vehicle",
                        verbose_name="차량",
                    ),
                ),
            ],
            options={
                "verbose_name": "경매 이력",
                "verbose_name_plural": "경매 이력 목록",
                "db_table": "auction_histories",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Auction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "승인대기"),
                            ("AUCTION_ACTIVE", "경매진행"),
                            ("AUCTION_ENDED", "경매종료"),
                            ("TRANSACTION_COMPLETE", "거래완료"),
                        ],
                        default="PENDING",
                        max_length=30,
                        verbose_name="상태",
                    ),
                ),
                (
                    "start_time",
                    models.DateTimeField(blank=True, null=True, verbose_name="경매시작시간"),
                ),
                (
                    "end_time",
                    models.DateTimeField(blank=True, null=True, verbose_name="경매종료시간"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="거래완료시간"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "vehicle",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="auction",
                        to="vehicles.vehicle",
                        verbose_name="차량",
                    ),
                ),
            ],
            options={
                "verbose_name": "경매",
                "verbose_name_plural": "경매 목록",
                "db_table": "auctions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="auction",
            index=models.Index(
                fields=["status", "end_time"], name="auctions_status_3d6271_idx"
            ),
        ),
    ]
