# Generated by Django 4.2 on 2025-10-07 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=50, unique=True, verbose_name="브랜드명"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "브랜드",
                "verbose_name_plural": "브랜드 목록",
                "db_table": "brands",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="CarType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="차종명")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="car_types",
                        to="vehicles.brand",
                        verbose_name="브랜드",
                    ),
                ),
            ],
            options={
                "verbose_name": "차종",
                "verbose_name_plural": "차종 목록",
                "db_table": "car_types",
                "ordering": ["brand", "name"],
            },
        ),
        migrations.CreateModel(
            name="Model",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="모델명")),
                (
                    "year_start",
                    models.IntegerField(blank=True, null=True, verbose_name="출시년도"),
                ),
                (
                    "year_end",
                    models.IntegerField(blank=True, null=True, verbose_name="단종년도"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "car_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="models",
                        to="vehicles.cartype",
                        verbose_name="차종",
                    ),
                ),
            ],
            options={
                "verbose_name": "모델",
                "verbose_name_plural": "모델 목록",
                "db_table": "models",
                "ordering": ["car_type", "year_start", "name"],
            },
        ),
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField(verbose_name="연식")),
                ("first_registration_date", models.DateField(verbose_name="최초등록일")),
                ("color", models.CharField(max_length=50, verbose_name="색상")),
                (
                    "fuel_type",
                    models.CharField(
                        choices=[
                            ("lpg", "LPG"),
                            ("gasoline", "가솔린"),
                            ("diesel", "디젤"),
                            ("hybrid", "하이브리드"),
                            ("electric", "전기"),
                            ("bifuel", "바이퓨얼"),
                        ],
                        max_length=20,
                        verbose_name="연료타입",
                    ),
                ),
                (
                    "transmission",
                    models.CharField(
                        choices=[("auto", "자동"), ("manual", "수동")],
                        max_length=10,
                        verbose_name="변속기",
                    ),
                ),
                ("mileage", models.PositiveIntegerField(verbose_name="주행거리")),
                ("region", models.CharField(max_length=50, verbose_name="지역")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "승인대기"),
                            ("AUCTION_ACTIVE", "경매진행"),
                            ("AUCTION_ENDED", "경매종료"),
                            ("TRANSACTION_COMPLETE", "거래완료"),
                        ],
                        default="PENDING",
                        max_length=30,
                        verbose_name="상태",
                    ),
                ),
                ("auction_start_time", models.DateTimeField(blank=True, null=True)),
                ("auction_end_time", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="vehicles.model",
                        verbose_name="모델",
                    ),
                ),
            ],
            options={
                "verbose_name": "차량",
                "verbose_name_plural": "차량 목록",
                "db_table": "vehicles",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VehicleImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="vehicle_images/%Y/%m/%d/", verbose_name="이미지"
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(default=False, verbose_name="대표이미지"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="vehicles.vehicle",
                        verbose_name="차량",
                    ),
                ),
            ],
            options={
                "verbose_name": "차량 이미지",
                "verbose_name_plural": "차량 이미지 목록",
                "db_table": "vehicle_images",
                "ordering": ["-is_primary", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="vehicle",
            index=models.Index(
                fields=["status", "auction_end_time"], name="vehicles_status_88a93c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vehicle",
            index=models.Index(fields=["model"], name="vehicles_model_i_3aa119_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="model",
            unique_together={("car_type", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="cartype",
            unique_together={("brand", "name")},
        ),
    ]
